FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    mlflow \
    xgboost \
    pandas \
    numpy \
    pydantic \
    redis \
    evidently==0.4.16

RUN mkdir -p /app/logs

COPY app/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
